### ISSUE TITLE
You put "freamwork" instead of "framework". Please fix it in your tags.

### ISSUE THREAD

**Issue by raax7** [python-bale-bot/python-bale-bot#109]
### what is your bale bot version?

You put "freamwork" instead of "framework". Please fix it in your tags.

### Reproduction Steps

You put "freamwork" instead of "framework". Please fix it in your tags.

### Exception Result

You put "freamwork" instead of "framework". Please fix it in your tags.

### System Information

You put "freamwork" instead of "framework". Please fix it in your tags.

**Comment by kian-ahmadian** [comment]
سلام عزیز وقتتون بخیر
از گزارش شما بسیار سپاسگزاریم
**این مورد رفع شد**
