### ISSUE TITLE
bot unresponsive when clicked on callback

### ISSUE THREAD

**Issue by okaeiz** [python-bale-bot/python-bale-bot#12]
### what is your bale bot version?

python-bale-bot==2.4.2

### Reproduction Steps

I want to edit the post which bot has sent using this:

`await callback.message.edit("some text)`

When I do this, I get dozens of errors and Bale webpage gets unresponsive.
The last line of these errors is as follows:

`RuntimeError: Event loop is closed`

The problem seems to be with asyncio, I reckon.

### Exception Result

 I expect the message to be edited instead of sending a new message.

**Comment by okaeiz** [comment]
I will send my code. The case is somewhat strange.
When I do not include any components as the argument, the error happens. But when I add components - such as inline keyboards - the problems disappears.

The error itself is too long and annoying. When I am using bale on its web version, by clicking on the button which sends the callback and `await callback.message.edit()` has to run, the webpage suddenly crashes and I have to refresh it. The code above runs, of course. But the whole program stops working afterwards.

**Comment by kian-ahmadian** [comment]
The website issue is for the messaging team and **will not be included in our package**, and as long as you don't edit the messaging component, it won't be a problem.
But regarding other problems, **please enter the repositories of people who have used this package**. And if you still have a problem, report it here.

**Comment by okaeiz** [comment]
I think you misunderstood the issue.
I do not leave the method empty. I only add the "text" argument. When I do so, the error happens. But when I add other components like inline keyboards, the problem disappears.

**Comment by kian-ahmadian** [comment]
So please post your error, no matter how long it is, from beginning to end
