### ISSUE TITLE
مشکل  اساسی

### ISSUE THREAD

**Issue by Daradege** [python-bale-bot/python-bale-bot#127]
### what is your bale bot version?

2.5.0

### Reproduction Steps

کار با api
api هوش مصنوعی که طول میکشه generate کنه

### Exception Result

وقتی به یه api رکوئست میزنم و طول میکشه رباتم متوقف میشه
چیکار کنم؟

**Comment by kian-ahmadian** [comment]
تکه کدی که با استفاده از اون سعی در دریافت اطلاعات رو دارید ارسال نمایید

**Comment by Daradege** [comment]
```
async def on_message(m):
    await m.reply(requests.get("http://localhost").text)
```
میخوام بدون aiohttp انجام بدم
میشه؟

**Comment by kian-ahmadian** [comment]
بهتر هست با aiohttp انجام بشه تا همروندی در بین فانکشن ها با تعداد بالا بهتر انجام بشه
توصیه میکنم اگر مشکلی با aiohttp دارین بفرمایید
