### ISSUE TITLE
مشکل در نسخه گیت

### ISSUE THREAD

**Issue by dark-ghost-123** [python-bale-bot/python-bale-bot#137]
### what is your bale bot version?

2.5.0

### Reproduction Steps

برنچ مستر که الان روی گیت هاب هست پر از مشکلات مختلفه.
کاش نسخه مستر رو به نسخه ای که روی مخزن پایتون هست برگردونید تا نسخه جدید اماده بشه.

### Exception Result

ممنون از تلاشتون برای ساخت چنین کتابخونه خوبی.❤❤
وقت کنم حتما تو روند توسعش کمکتون میکنم.

**Comment by dark-ghost-123** [comment]
الان داشتم کامیت هات رو نگاه میکردم. تو کامیت [ریفکتور](https://github.com/python-bale-bot/python-bale-bot/commit/8daed681ddd8af91f2400e2bf3dae40de902e588) خیلی خطا ایجاد شده. و عمدتا بخاطر تغییر اسامی یا حذف بعضی موارد بوده که با تغیرشون فایلای دیگه تغییر داده نشدن.

**Comment by kian-ahmadian** [comment]
درود بر شما و دقت تان
نسخه جدید تقریبا آماده شده و بنابراین یک سری از تغییرات کوچکی که موجب برطرف شدن این اشکال شده اند تا روز های آینده و قبل از نسخه بعدی کامیت میشوند.
در نسخه فعلی علاوه بر این مشکل، در هنگام نصب مشکلاتی وجود دارد که به زودی به آن هم میپردازیم

در صورت تمایل نیز میتوانید ایده های خود را با باز کردن گفتگویی جدید در دسته بندی ایده ها، به گوش ما برسانید. توصیه می‌کنیم تا زمانی که تغییرات جدید اعمال نشده اند درخواست تغییری (PRs) ارسال ننمایید.
