### ISSUE TITLE
Not closing the bot when using the Bot.close() method

### ISSUE THREAD

**Issue by erfan-s** [python-bale-bot/python-bale-bot#16]
### what is your bale bot version?

2.4.3

### Reproduction Steps

**I have written my bot as object oriented, but when I try to close the bot using the `Bot.close()` method, some parts like the updater are still running.**

```py
...
await bot.close()
```

### System Information

Nothing

**Comment by kian-ahmadian** [comment]
Hey @erfan-s 

**We fix this soon.**
Thanks for your issues
