### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by salehsh1385** [python-bale-bot/python-bale-bot#23]
### what is your bale bot version?

Lastest 

### Reproduction Steps

سلام بات در گروه مدیره و همه دسترسی ها رو دادم 

```python
...
@bot.listen("on_message")
async def message(message: bale.Message):
  if message.content == "/addme":
    chat = await bot.get_chat("username")
    await chat.add_user(message.author)
```

### Exception Result

Error on_message 0: Internal server error

**Comment by kian-ahmadian** [comment]
**با سلام و وقت بخیر، مشکل گفته شده بررسی شد. در صورتی که تمامی مجوز های لازم به ربات داده شده باشد و کاربر به صورت کلی در گروه نباشد ارور `InternalError` داده نمیشود و بدون مشکل کار انجام خواهد شد**

**Comment by salehsh1385** [comment]
ولی الان میده

**Comment by kian-ahmadian** [comment]
لطفا همه شرایط رو بررسی کنین، ببینین آیا خودتون داخل اون گروه هستین یا خیر، ربات در اون گروه امکانات رو داره یا خیر
کاربری که میخواین اضافه اش کنین در بخش تنظیمات حریم خصوصی، گزینه اضافه کردن به گروه رو بر روی چه حالتی قرار داده

**همه این مورد هارا بررسی کنین**

**Comment by salehsh1385** [comment]
همه رو بررسی کردم اما نشده

**Comment by kian-ahmadian** [comment]
شناسه رو به چه شکل میدین؟

**Comment by salehsh1385** [comment]
Int

**Comment by kian-ahmadian** [comment]
```python
...
chat = await bot.get_chat(123 or "123")
user = await bot.get_user(123 or "123")
await chat.add_user(user or message.author)
```

**Comment by salehsh1385** [comment]
درست شد خیلی ممنونم 🙏🙏🙏🙏🙏🙏
نمیشه با یوز نیم عضو کرد؟؟؟

**Comment by kian-ahmadian** [comment]
**تنها میتونین در کانال ها و یا گروه های شناسه دار، از یوزرنیم آن ها در دریافت چت استفاده کنین**

**Comment by salehsh1385** [comment]
سلام ببخشید آقای احمدیان من سوال میکنم چون کسی جز شما نیست جواب بنده رو بده چه طوری میتونم تمام چت آیدی های یک گروه یا کانال رو بگیرم؟ 
من بازم معذرت می‌خوام 🙏
