### ISSUE TITLE
Problem in method reply and delete_message

### ISSUE THREAD

**Issue by 0Mehrdad0** [python-bale-bot/python-bale-bot#25]
### what is your bale bot version?

V2.4.5

### Reproduction Steps

method reply => error (Internal server error)
method delete_message => error(message not found) in callback

These problems have been observed from late yesterday

### Exception Result

reply and delete(message)

**Comment by kian-ahmadian** [comment]
Hey @0Mehrdad0, Thanks for your issus. I hope to Bale is Fix the bugs.

**Comment by kian-ahmadian** [comment]
I announce every things about this problems in The issue.

**Comment by kian-ahmadian** [comment]
At 10:40 p.m the bugs fixed by Bale.
Good Lock
