### ISSUE TITLE
[BUG] `parse_time` function doesn't work

### ISSUE THREAD

**Issue by MoSi8160** [python-bale-bot/python-bale-bot#72]
### what is your bale bot version?

2.4.9

### Reproduction Steps

```
from bale import Bot, Update, Message

client = Bot(token="token")

@client.event
async def on_ready():
	print(client.user.username, "is Ready!")

@client.event
async def on_update(update: Update):
	print(update.update_id)

@client.event
async def on_message(message: Message):
	if message.content == '/start': # to get caption or text of message
		await message.reply('Hi, from python-bale-bot to everyone!')
		if message.chat.is_group_chat:
			await message.reply("It's is a special Hi for groups!") # work when message sent in a group

# See https://docs.python-bale-bot.ir/en/stable/event.html to get more information about events!

client.run()
```

### Exception Result

[2024-01-22 11:27:01] [CRITICAL] bale.updater: Somthing was happened when we process Update data from bale
Traceback (most recent call last):
  File "d:\MaMaD\سفارش غذا\bale\updater.py", line 78, in action_getupdates
    updates = await self.bot.get_updates(offset=self._last_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MaMaD\سفارش غذا\bale\bot.py", line 1937, in get_updates
    result = [Update.from_dict(data=update_payload, bot=self) for update_payload in response.result       
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MaMaD\سفارش غذا\bale\update.py", line 63, in from_dict
    data['message'] = Message.from_dict(data.pop('message', None), bot)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MaMaD\سفارش غذا\bale\message.py", line 165, in from_dict
    data["edit_date"] = parse_time(data.pop('edit_date', None))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MaMaD\سفارش غذا\bale\helpers.py", line 52, in parse_time
    return datetime.fromtimestamp(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by kian-ahmadian** [comment]
سلام عزیز وقتتون بخیر
**مشکل ظاهراً حل شده، لطفا بررسی کنید و اطلاع بدید**

برای این کار یک بار پکیج و حذف کنید و سپس از طریق گیت اون رو نصب کنید

**Comment by kian-ahmadian** [comment]
سلام عزیز وقت بخیر
**در حال حاضر به نظر میرسه این مشکل حل شده؛ لطفا صحت این موضوع رو بررسی کرده و به ما اطلاع رسانی کنید**

توجه: در نظر داشته باشید میبایست یکبار کتابخانه را حذف کرده و سپس دوباره آن را از طریق گیت نصب نمایید
